let link =
  "https://api.sportradar.us/soccer-t3/eu/en/schedules/2021-03-26/schedule.json?api_key=bq4g8trvq6grz8zevvcnu27f";

export const schedule = {
  generated_at: "2021-03-03T04:50:28+00:00",
  schema:
    "http://schemas.sportradar.com/bsa/soccer/v1/json/endpoints/soccer/schedule.json",
  sport_events: [
    {
      id: "sr:match:23301053",
      scheduled: "2021-03-03T10:30:00+00:00",
      start_time_tbd: false,
      status: "not_started",
      tournament_round: {
        type: "group",
        number: 28,
        phase: "regular season",
      },
      season: {
        id: "sr:season:78091",
        name: "Super Lig 20/21",
        start_date: "2020-09-11",
        end_date: "2021-05-17",
        year: "20/21",
        tournament_id: "sr:tournament:52",
      },
      tournament: {
        id: "sr:tournament:52",
        name: "Super Lig",
        sport: {
          id: "sr:sport:1",
          name: "Soccer",
        },
        category: {
          id: "sr:category:46",
          name: "Turkey",
          country_code: "TUR",
        },
      },
      competitors: [
        {
          id: "sr:competitor:55603",
          name: "Buyuksehir Belediye Erzurumspor",
          country: "Turkey",
          country_code: "TUR",
          abbreviation: "BUY",
          qualifier: "home",
        },
        {
          id: "sr:competitor:4954",
          name: "Fatih Karagumruk SK",
          country: "Turkey",
          country_code: "TUR",
          abbreviation: "KAR",
          qualifier: "away",
        },
      ],
      venue: {
        id: "sr:venue:5478",
        name: "Kazim Karabekir Stadyumu",
        capacity: 23700,
        city_name: "Erzurum",
        country_name: "Turkey",
        map_coordinates: "39.911185,41.237953",
        country_code: "TUR",
      },
    },
    {
      id: "sr:match:23301055",
      scheduled: "2021-03-03T13:00:00+00:00",
      start_time_tbd: false,
      status: "not_started",
      tournament_round: {
        type: "group",
        number: 28,
        phase: "regular season",
      },
      season: {
        id: "sr:season:78091",
        name: "Super Lig 20/21",
        start_date: "2020-09-11",
        end_date: "2021-05-17",
        year: "20/21",
        tournament_id: "sr:tournament:52",
      },
      tournament: {
        id: "sr:tournament:52",
        name: "Super Lig",
        sport: {
          id: "sr:sport:1",
          name: "Soccer",
        },
        category: {
          id: "sr:category:46",
          name: "Turkey",
          country_code: "TUR",
        },
      },
      competitors: [
        {
          id: "sr:competitor:3076",
          name: "Sivasspor",
          country: "Turkey",
          country_code: "TUR",
          abbreviation: "SIV",
          qualifier: "home",
        },
        {
          id: "sr:competitor:3091",
          name: "Hatayspor",
          country: "Turkey",
          country_code: "TUR",
          abbreviation: "HAT",
          qualifier: "away",
        },
      ],
      venue: {
        id: "sr:venue:2101",
        name: "Yeni Sivas 4 Eylul Stadium",
        capacity: 27532,
        city_name: "Sivas",
        country_name: "Turkey",
        map_coordinates: "39.741028,37.003307",
        country_code: "TUR",
      },
    },
    {
      id: "sr:match:23301065",
      scheduled: "2021-03-03T13:00:00+00:00",
      start_time_tbd: false,
      status: "not_started",
      tournament_round: {
        type: "group",
        number: 28,
        phase: "regular season",
      },
      season: {
        id: "sr:season:78091",
        name: "Super Lig 20/21",
        start_date: "2020-09-11",
        end_date: "2021-05-17",
        year: "20/21",
        tournament_id: "sr:tournament:52",
      },
      tournament: {
        id: "sr:tournament:52",
        name: "Super Lig",
        sport: {
          id: "sr:sport:1",
          name: "Soccer",
        },
        category: {
          id: "sr:category:46",
          name: "Turkey",
          country_code: "TUR",
        },
      },
      competitors: [
        {
          id: "sr:competitor:3086",
          name: "Istanbul Basaksehir FK",
          country: "Turkey",
          country_code: "TUR",
          abbreviation: "BAS",
          qualifier: "home",
        },
        {
          id: "sr:competitor:3085",
          name: "Konyaspor Club",
          country: "Turkey",
          country_code: "TUR",
          abbreviation: "KON",
          qualifier: "away",
        },
      ],
      venue: {
        id: "sr:venue:14806",
        name: "Basaksehir Fatih Terim Stadium",
        capacity: 17156,
        city_name: "Istanbul",
        country_name: "Turkey",
        map_coordinates: "41.122784,28.808701",
        country_code: "TUR",
      },
    },
    {
      id: "sr:match:25565492",
      scheduled: "2021-03-03T13:00:00+00:00",
      start_time_tbd: false,
      status: "cancelled",
      tournament_round: {
        type: "cup",
        name: "round_of_64",
        cup_round_match_number: 1,
        cup_round_matches: 1,
        phase: "playoffs",
      },
      season: {
        id: "sr:season:81280",
        name: "UEFA Youth League 2021",
        start_date: "2021-03-02",
        end_date: "2021-05-20",
        year: "2021",
        tournament_id: "sr:tournament:2324",
      },
      tournament: {
        id: "sr:tournament:2324",
        name: "UEFA Youth League",
        sport: {
          id: "sr:sport:1",
          name: "Soccer",
        },
        category: {
          id: "sr:category:392",
          name: "International Youth",
        },
      },
      competitors: [
        {
          id: "sr:competitor:90124",
          name: "Chelsea FC",
          country: "England",
          country_code: "ENG",
          abbreviation: "CFC",
          qualifier: "home",
        },
        {
          id: "sr:competitor:224772",
          name: "FC RB Salzburg",
          abbreviation: "SAL",
          qualifier: "away",
        },
      ],
    },
    {
      id: "sr:match:23301061",
      scheduled: "2021-03-03T16:00:00+00:00",
      start_time_tbd: false,
      status: "not_started",
      tournament_round: {
        type: "group",
        number: 28,
        phase: "regular season",
      },
      season: {
        id: "sr:season:78091",
        name: "Super Lig 20/21",
        start_date: "2020-09-11",
        end_date: "2021-05-17",
        year: "20/21",
        tournament_id: "sr:tournament:52",
      },
      tournament: {
        id: "sr:tournament:52",
        name: "Super Lig",
        sport: {
          id: "sr:sport:1",
          name: "Soccer",
        },
        category: {
          id: "sr:category:46",
          name: "Turkey",
          country_code: "TUR",
        },
      },
      competitors: [
        {
          id: "sr:competitor:3072",
          name: "Kayserispor",
          country: "Turkey",
          country_code: "TUR",
          abbreviation: "KAY",
          qualifier: "home",
        },
        {
          id: "sr:competitor:3064",
          name: "Caykur Rizespor",
          country: "Turkey",
          country_code: "TUR",
          abbreviation: "RIZ",
          qualifier: "away",
        },
      ],
      venue: {
        id: "sr:venue:1215",
        name: "Kadir Has Stadium",
        capacity: 32864,
        city_name: "Kayseri",
        country_name: "Turkey",
        map_coordinates: "38.737289,35.423134",
        country_code: "TUR",
      },
    },
    {
      id: "sr:match:23301067",
      scheduled: "2021-03-03T16:00:00+00:00",
      start_time_tbd: false,
      status: "not_started",
      tournament_round: {
        type: "group",
        number: 28,
        phase: "regular season",
      },
      season: {
        id: "sr:season:78091",
        name: "Super Lig 20/21",
        start_date: "2020-09-11",
        end_date: "2021-05-17",
        year: "20/21",
        tournament_id: "sr:tournament:52",
      },
      tournament: {
        id: "sr:tournament:52",
        name: "Super Lig",
        sport: {
          id: "sr:sport:1",
          name: "Soccer",
        },
        category: {
          id: "sr:category:46",
          name: "Turkey",
          country_code: "TUR",
        },
      },
      competitors: [
        {
          id: "sr:competitor:3103",
          name: "MKE Ankaragucu",
          country: "Turkey",
          country_code: "TUR",
          abbreviation: "ANK",
          qualifier: "home",
        },
        {
          id: "sr:competitor:3061",
          name: "Galatasaray SK",
          country: "Turkey",
          country_code: "TUR",
          abbreviation: "GAL",
          qualifier: "away",
        },
      ],
      venue: {
        id: "sr:venue:39091",
        name: "Eryaman Stadyumu",
        capacity: 22000,
        city_name: "Ankara",
        country_name: "Turkey",
        map_coordinates: "39.980139, 32.613861",
        country_code: "TUR",
      },
    },
    {
      id: "sr:match:23391061",
      scheduled: "2021-03-03T17:30:00+00:00",
      start_time_tbd: false,
      status: "not_started",
      tournament_round: {
        type: "group",
        number: 25,
        phase: "regular season",
      },
      season: {
        id: "sr:season:77547",
        name: "Serie A 20/21",
        start_date: "2020-09-19",
        end_date: "2021-05-23",
        year: "20/21",
        tournament_id: "sr:tournament:23",
      },
      tournament: {
        id: "sr:tournament:23",
        name: "Serie A",
        sport: {
          id: "sr:sport:1",
          name: "Soccer",
        },
        category: {
          id: "sr:category:31",
          name: "Italy",
          country_code: "ITA",
        },
      },
      competitors: [
        {
          id: "sr:competitor:2793",
          name: "Sassuolo Calcio",
          country: "Italy",
          country_code: "ITA",
          abbreviation: "SAS",
          qualifier: "home",
        },
        {
          id: "sr:competitor:2714",
          name: "SSC Napoli",
          country: "Italy",
          country_code: "ITA",
          abbreviation: "NAP",
          qualifier: "away",
        },
      ],
      venue: {
        id: "sr:venue:2031",
        name: "Mapei Stadium",
        capacity: 21584,
        city_name: "Reggio Emilia",
        country_name: "Italy",
        map_coordinates: "44.713360,10.649211",
        country_code: "ITA",
      },
    },
    {
      id: "sr:match:22650869",
      scheduled: "2021-03-03T18:00:00+00:00",
      start_time_tbd: false,
      status: "not_started",
      tournament_round: {
        type: "group",
        number: 28,
        phase: "regular season",
      },
      season: {
        id: "sr:season:77239",
        name: "Ligue 1 20/21",
        start_date: "2020-08-21",
        end_date: "2021-05-31",
        year: "20/21",
        tournament_id: "sr:tournament:34",
      },
      tournament: {
        id: "sr:tournament:34",
        name: "Ligue 1",
        sport: {
          id: "sr:sport:1",
          name: "Soccer",
        },
        category: {
          id: "sr:category:7",
          name: "France",
          country_code: "FRA",
        },
      },
      competitors: [
        {
          id: "sr:competitor:1715",
          name: "Stade Brestois 29",
          country: "France",
          country_code: "FRA",
          abbreviation: "STB",
          qualifier: "home",
        },
        {
          id: "sr:competitor:1686",
          name: "Dijon FCO",
          country: "France",
          country_code: "FRA",
          abbreviation: "DIJ",
          qualifier: "away",
        },
      ],
      venue: {
        id: "sr:venue:1858",
        name: "Stade Francis-Le Ble",
        capacity: 15097,
        city_name: "Brest",
        country_name: "France",
        map_coordinates: "48.402932,-4.461694",
        country_code: "FRA",
      },
    },
    {
      id: "sr:match:22650873",
      scheduled: "2021-03-03T18:00:00+00:00",
      start_time_tbd: false,
      status: "not_started",
      tournament_round: {
        type: "group",
        number: 28,
        phase: "regular season",
      },
      season: {
        id: "sr:season:77239",
        name: "Ligue 1 20/21",
        start_date: "2020-08-21",
        end_date: "2021-05-31",
        year: "20/21",
        tournament_id: "sr:tournament:34",
      },
      tournament: {
        id: "sr:tournament:34",
        name: "Ligue 1",
        sport: {
          id: "sr:sport:1",
          name: "Soccer",
        },
        category: {
          id: "sr:category:7",
          name: "France",
          country_code: "FRA",
        },
      },
      competitors: [
        {
          id: "sr:competitor:1649",
          name: "Olympique Lyonnais",
          country: "France",
          country_code: "FRA",
          abbreviation: "OL",
          qualifier: "home",
        },
        {
          id: "sr:competitor:1658",
          name: "Stade Rennais FC",
          country: "France",
          country_code: "FRA",
          abbreviation: "REN",
          qualifier: "away",
        },
      ],
      venue: {
        id: "sr:venue:17406",
        name: "Groupama Stadium",
        capacity: 59186,
        city_name: "Lyon",
        country_name: "France",
        map_coordinates: "45.766912,4.980991",
        country_code: "FRA",
      },
    },
    {
      id: "sr:match:22650875",
      scheduled: "2021-03-03T18:00:00+00:00",
      start_time_tbd: false,
      status: "not_started",
      tournament_round: {
        type: "group",
        number: 28,
        phase: "regular season",
      },
      season: {
        id: "sr:season:77239",
        name: "Ligue 1 20/21",
        start_date: "2020-08-21",
        end_date: "2021-05-31",
        year: "20/21",
        tournament_id: "sr:tournament:34",
      },
      tournament: {
        id: "sr:tournament:34",
        name: "Ligue 1",
        sport: {
          id: "sr:sport:1",
          name: "Soccer",
        },
        category: {
          id: "sr:category:7",
          name: "France",
          country_code: "FRA",
        },
      },
      competitors: [
        {
          id: "sr:competitor:1651",
          name: "FC Metz",
          country: "France",
          country_code: "FRA",
          abbreviation: "FCM",
          qualifier: "home",
        },
        {
          id: "sr:competitor:1684",
          name: "Angers SCO",
          country: "France",
          country_code: "FRA",
          abbreviation: "ANG",
          qualifier: "away",
        },
      ],
      venue: {
        id: "sr:venue:840",
        name: "Stade Saint Symphorien",
        capacity: 26661,
        city_name: "Metz",
        country_name: "France",
        map_coordinates: "49.109813,6.159511",
        country_code: "FRA",
      },
    },
    {
      id: "sr:match:22650881",
      scheduled: "2021-03-03T18:00:00+00:00",
      start_time_tbd: false,
      status: "not_started",
      tournament_round: {
        type: "group",
        number: 28,
        phase: "regular season",
      },
      season: {
        id: "sr:season:77239",
        name: "Ligue 1 20/21",
        start_date: "2020-08-21",
        end_date: "2021-05-31",
        year: "20/21",
        tournament_id: "sr:tournament:34",
      },
      tournament: {
        id: "sr:tournament:34",
        name: "Ligue 1",
        sport: {
          id: "sr:sport:1",
          name: "Soccer",
        },
        category: {
          id: "sr:category:7",
          name: "France",
          country_code: "FRA",
        },
      },
      competitors: [
        {
          id: "sr:competitor:1661",
          name: "OGC Nice",
          country: "France",
          country_code: "FRA",
          abbreviation: "NIC",
          qualifier: "home",
        },
        {
          id: "sr:competitor:1663",
          name: "Olympique Nimes",
          country: "France",
          country_code: "FRA",
          abbreviation: "NIM",
          qualifier: "away",
        },
      ],
      venue: {
        id: "sr:venue:13184",
        name: "Allianz Rivera",
        capacity: 36178,
        city_name: "Nice",
        country_name: "France",
        map_coordinates: "43.705139, 7.192583",
        country_code: "FRA",
      },
    },
    {
      id: "sr:match:22650883",
      scheduled: "2021-03-03T18:00:00+00:00",
      start_time_tbd: false,
      status: "not_started",
      tournament_round: {
        type: "group",
        number: 28,
        phase: "regular season",
      },
      season: {
        id: "sr:season:77239",
        name: "Ligue 1 20/21",
        start_date: "2020-08-21",
        end_date: "2021-05-31",
        year: "20/21",
        tournament_id: "sr:tournament:34",
      },
      tournament: {
        id: "sr:tournament:34",
        name: "Ligue 1",
        sport: {
          id: "sr:sport:1",
          name: "Soccer",
        },
        category: {
          id: "sr:category:7",
          name: "France",
          country_code: "FRA",
        },
      },
      competitors: [
        {
          id: "sr:competitor:1678",
          name: "AS Saint-Etienne",
          country: "France",
          country_code: "FRA",
          abbreviation: "STE",
          qualifier: "home",
        },
        {
          id: "sr:competitor:1648",
          name: "RC Lens",
          country: "France",
          country_code: "FRA",
          abbreviation: "RCL",
          qualifier: "away",
        },
      ],
      venue: {
        id: "sr:venue:845",
        name: "Stade Geoffroy Guichard",
        capacity: 42000,
        city_name: "Saint Etienne",
        country_name: "France",
        map_coordinates: "45.460833,4.390278",
        country_code: "FRA",
      },
    },
    {
      id: "sr:match:23204343",
      scheduled: "2021-03-03T18:00:00+00:00",
      start_time_tbd: false,
      status: "not_started",
      tournament_round: {
        type: "group",
        number: 29,
        phase: "regular season",
      },
      season: {
        id: "sr:season:77179",
        name: "Premier League 20/21",
        start_date: "2020-09-12",
        end_date: "2021-05-24",
        year: "20/21",
        tournament_id: "sr:tournament:17",
      },
      tournament: {
        id: "sr:tournament:17",
        name: "Premier League",
        sport: {
          id: "sr:sport:1",
          name: "Soccer",
        },
        category: {
          id: "sr:category:1",
          name: "England",
          country_code: "ENG",
        },
      },
      competitors: [
        {
          id: "sr:competitor:6",
          name: "Burnley FC",
          country: "England",
          country_code: "ENG",
          abbreviation: "BUR",
          qualifier: "home",
        },
        {
          id: "sr:competitor:31",
          name: "Leicester City FC",
          country: "England",
          country_code: "ENG",
          abbreviation: "LEI",
          qualifier: "away",
        },
      ],
      venue: {
        id: "sr:venue:806",
        name: "Turf Moor",
        capacity: 21401,
        city_name: "Burnley",
        country_name: "England",
        map_coordinates: "53.789167,-2.230278",
        country_code: "ENG",
      },
    },
    {
      id: "sr:match:23204353",
      scheduled: "2021-03-03T18:00:00+00:00",
      start_time_tbd: false,
      status: "not_started",
      tournament_round: {
        type: "group",
        number: 29,
        phase: "regular season",
      },
      season: {
        id: "sr:season:77179",
        name: "Premier League 20/21",
        start_date: "2020-09-12",
        end_date: "2021-05-24",
        year: "20/21",
        tournament_id: "sr:tournament:17",
      },
      tournament: {
        id: "sr:tournament:17",
        name: "Premier League",
        sport: {
          id: "sr:sport:1",
          name: "Soccer",
        },
        category: {
          id: "sr:category:1",
          name: "England",
          country_code: "ENG",
        },
      },
      competitors: [
        {
          id: "sr:competitor:15",
          name: "Sheffield United FC",
          country: "England",
          country_code: "ENG",
          abbreviation: "SHU",
          qualifier: "home",
        },
        {
          id: "sr:competitor:40",
          name: "Aston Villa FC",
          country: "England",
          country_code: "ENG",
          abbreviation: "VIL",
          qualifier: "away",
        },
      ],
      venue: {
        id: "sr:venue:598",
        name: "Bramall Lane",
        capacity: 32702,
        city_name: "Sheffield",
        country_name: "England",
        map_coordinates: "53.370278,-1.470833",
        country_code: "ENG",
      },
    },
    {
      id: "sr:match:23391043",
      scheduled: "2021-03-03T19:45:00+00:00",
      start_time_tbd: false,
      status: "not_started",
      tournament_round: {
        type: "group",
        number: 25,
        phase: "regular season",
      },
      season: {
        id: "sr:season:77547",
        name: "Serie A 20/21",
        start_date: "2020-09-19",
        end_date: "2021-05-23",
        year: "20/21",
        tournament_id: "sr:tournament:23",
      },
      tournament: {
        id: "sr:tournament:23",
        name: "Serie A",
        sport: {
          id: "sr:sport:1",
          name: "Soccer",
        },
        category: {
          id: "sr:category:31",
          name: "Italy",
          country_code: "ITA",
        },
      },
      competitors: [
        {
          id: "sr:competitor:2686",
          name: "Atalanta BC",
          country: "Italy",
          country_code: "ITA",
          abbreviation: "ATA",
          qualifier: "home",
        },
        {
          id: "sr:competitor:2718",
          name: "FC Crotone",
          country: "Italy",
          country_code: "ITA",
          abbreviation: "COR",
          qualifier: "away",
        },
      ],
      venue: {
        id: "sr:venue:588",
        name: "Gewiss Stadium",
        capacity: 26393,
        city_name: "Bergamo",
        country_name: "Italy",
        map_coordinates: "45.708889,9.680833",
        country_code: "ITA",
      },
    },
    {
      id: "sr:match:23391045",
      scheduled: "2021-03-03T19:45:00+00:00",
      start_time_tbd: false,
      status: "not_started",
      tournament_round: {
        type: "group",
        number: 25,
        phase: "regular season",
      },
      season: {
        id: "sr:season:77547",
        name: "Serie A 20/21",
        start_date: "2020-09-19",
        end_date: "2021-05-23",
        year: "20/21",
        tournament_id: "sr:tournament:23",
      },
      tournament: {
        id: "sr:tournament:23",
        name: "Serie A",
        sport: {
          id: "sr:sport:1",
          name: "Soccer",
        },
        category: {
          id: "sr:category:31",
          name: "Italy",
          country_code: "ITA",
        },
      },
      competitors: [
        {
          id: "sr:competitor:2759",
          name: "Benevento Calcio",
          country: "Italy",
          country_code: "ITA",
          abbreviation: "BEN",
          qualifier: "home",
        },
        {
          id: "sr:competitor:2701",
          name: "Hellas Verona",
          country: "Italy",
          country_code: "ITA",
          abbreviation: "VER",
          qualifier: "away",
        },
      ],
      venue: {
        id: "sr:venue:2719",
        name: "Stadio Ciro Vigorito",
        capacity: 16867,
        city_name: "Benevento",
        country_name: "Italy",
        map_coordinates: "41.116470,14.781073",
        country_code: "ITA",
      },
    },
    {
      id: "sr:match:23391047",
      scheduled: "2021-03-03T19:45:00+00:00",
      start_time_tbd: false,
      status: "not_started",
      tournament_round: {
        type: "group",
        number: 25,
        phase: "regular season",
      },
      season: {
        id: "sr:season:77547",
        name: "Serie A 20/21",
        start_date: "2020-09-19",
        end_date: "2021-05-23",
        year: "20/21",
        tournament_id: "sr:tournament:23",
      },
      tournament: {
        id: "sr:tournament:23",
        name: "Serie A",
        sport: {
          id: "sr:sport:1",
          name: "Soccer",
        },
        category: {
          id: "sr:category:31",
          name: "Italy",
          country_code: "ITA",
        },
      },
      competitors: [
        {
          id: "sr:competitor:2719",
          name: "Cagliari Calcio",
          country: "Italy",
          country_code: "ITA",
          abbreviation: "CAG",
          qualifier: "home",
        },
        {
          id: "sr:competitor:2685",
          name: "Bologna FC",
          country: "Italy",
          country_code: "ITA",
          abbreviation: "BFC",
          qualifier: "away",
        },
      ],
      venue: {
        id: "sr:venue:22500",
        name: "Sardegna Arena",
        capacity: 16233,
        city_name: "Cagliari",
        country_name: "Italy",
        map_coordinates: "39.199813,9.137478",
        country_code: "ITA",
      },
    },
    {
      id: "sr:match:23391049",
      scheduled: "2021-03-03T19:45:00+00:00",
      start_time_tbd: false,
      status: "not_started",
      tournament_round: {
        type: "group",
        number: 25,
        phase: "regular season",
      },
      season: {
        id: "sr:season:77547",
        name: "Serie A 20/21",
        start_date: "2020-09-19",
        end_date: "2021-05-23",
        year: "20/21",
        tournament_id: "sr:tournament:23",
      },
      tournament: {
        id: "sr:tournament:23",
        name: "Serie A",
        sport: {
          id: "sr:sport:1",
          name: "Soccer",
        },
        category: {
          id: "sr:category:31",
          name: "Italy",
          country_code: "ITA",
        },
      },
      competitors: [
        {
          id: "sr:competitor:2693",
          name: "ACF Fiorentina",
          country: "Italy",
          country_code: "ITA",
          abbreviation: "FIO",
          qualifier: "home",
        },
        {
          id: "sr:competitor:2702",
          name: "AS Roma",
          country: "Italy",
          country_code: "ITA",
          abbreviation: "ROM",
          qualifier: "away",
        },
      ],
      venue: {
        id: "sr:venue:587",
        name: "Stadio Artemio Franchi",
        capacity: 47300,
        city_name: "Florence",
        country_name: "Italy",
        map_coordinates: "43.780822,11.282258",
        country_code: "ITA",
      },
    },
    {
      id: "sr:match:23391051",
      scheduled: "2021-03-03T19:45:00+00:00",
      start_time_tbd: false,
      status: "not_started",
      tournament_round: {
        type: "group",
        number: 25,
        phase: "regular season",
      },
      season: {
        id: "sr:season:77547",
        name: "Serie A 20/21",
        start_date: "2020-09-19",
        end_date: "2021-05-23",
        year: "20/21",
        tournament_id: "sr:tournament:23",
      },
      tournament: {
        id: "sr:tournament:23",
        name: "Serie A",
        sport: {
          id: "sr:sport:1",
          name: "Soccer",
        },
        category: {
          id: "sr:category:31",
          name: "Italy",
          country_code: "ITA",
        },
      },
      competitors: [
        {
          id: "sr:competitor:2713",
          name: "Genoa CFC",
          country: "Italy",
          country_code: "ITA",
          abbreviation: "GEN",
          qualifier: "home",
        },
        {
          id: "sr:competitor:2711",
          name: "Sampdoria Genoa",
          country: "Italy",
          country_code: "ITA",
          abbreviation: "SAM",
          qualifier: "away",
        },
      ],
      venue: {
        id: "sr:venue:682",
        name: "Luigi Ferraris",
        capacity: 36599,
        city_name: "Genoa",
        country_name: "Italy",
        map_coordinates: "44.416431,8.952428",
        country_code: "ITA",
      },
    },
    {
      id: "sr:match:23391057",
      scheduled: "2021-03-03T19:45:00+00:00",
      start_time_tbd: false,
      status: "not_started",
      tournament_round: {
        type: "group",
        number: 25,
        phase: "regular season",
      },
      season: {
        id: "sr:season:77547",
        name: "Serie A 20/21",
        start_date: "2020-09-19",
        end_date: "2021-05-23",
        year: "20/21",
        tournament_id: "sr:tournament:23",
      },
      tournament: {
        id: "sr:tournament:23",
        name: "Serie A",
        sport: {
          id: "sr:sport:1",
          name: "Soccer",
        },
        category: {
          id: "sr:category:31",
          name: "Italy",
          country_code: "ITA",
        },
      },
      competitors: [
        {
          id: "sr:competitor:2692",
          name: "AC Milan",
          country: "Italy",
          country_code: "ITA",
          abbreviation: "ACM",
          qualifier: "home",
        },
        {
          id: "sr:competitor:2695",
          name: "Udinese Calcio",
          country: "Italy",
          country_code: "ITA",
          abbreviation: "UDI",
          qualifier: "away",
        },
      ],
      venue: {
        id: "sr:venue:647",
        name: "Giuseppe Meazza",
        capacity: 80018,
        city_name: "Milan",
        country_name: "Italy",
        map_coordinates: "45.478025,9.124206",
        country_code: "ITA",
      },
    },
    {
      id: "sr:match:22650867",
      scheduled: "2021-03-03T20:00:00+00:00",
      start_time_tbd: false,
      status: "not_started",
      tournament_round: {
        type: "group",
        number: 28,
        phase: "regular season",
      },
      season: {
        id: "sr:season:77239",
        name: "Ligue 1 20/21",
        start_date: "2020-08-21",
        end_date: "2021-05-31",
        year: "20/21",
        tournament_id: "sr:tournament:34",
      },
      tournament: {
        id: "sr:tournament:34",
        name: "Ligue 1",
        sport: {
          id: "sr:sport:1",
          name: "Soccer",
        },
        category: {
          id: "sr:category:7",
          name: "France",
          country_code: "FRA",
        },
      },
      competitors: [
        {
          id: "sr:competitor:1645",
          name: "FC Girondins Bordeaux",
          country: "France",
          country_code: "FRA",
          abbreviation: "BOR",
          qualifier: "home",
        },
        {
          id: "sr:competitor:1644",
          name: "Paris Saint-Germain FC",
          country: "France",
          country_code: "FRA",
          abbreviation: "PSG",
          qualifier: "away",
        },
      ],
      venue: {
        id: "sr:venue:16269",
        name: "Matmut Atlantique",
        capacity: 42115,
        city_name: "Bordeaux",
        country_name: "France",
        map_coordinates: "44.897222,-0.561667",
        country_code: "FRA",
      },
    },
    {
      id: "sr:match:22650871",
      scheduled: "2021-03-03T20:00:00+00:00",
      start_time_tbd: false,
      status: "not_started",
      tournament_round: {
        type: "group",
        number: 28,
        phase: "regular season",
      },
      season: {
        id: "sr:season:77239",
        name: "Ligue 1 20/21",
        start_date: "2020-08-21",
        end_date: "2021-05-31",
        year: "20/21",
        tournament_id: "sr:tournament:34",
      },
      tournament: {
        id: "sr:tournament:34",
        name: "Ligue 1",
        sport: {
          id: "sr:sport:1",
          name: "Soccer",
        },
        category: {
          id: "sr:category:7",
          name: "France",
          country_code: "FRA",
        },
      },
      competitors: [
        {
          id: "sr:competitor:1643",
          name: "LOSC Lille",
          country: "France",
          country_code: "FRA",
          abbreviation: "LIL",
          qualifier: "home",
        },
        {
          id: "sr:competitor:1641",
          name: "Olympique Marseille",
          country: "France",
          country_code: "FRA",
          abbreviation: "OM",
          qualifier: "away",
        },
      ],
      venue: {
        id: "sr:venue:837",
        name: "Stade Pierre Mauroy",
        capacity: 50186,
        city_name: "Lille",
        country_name: "France",
        map_coordinates: "50.612005, 3.130613",
        country_code: "FRA",
      },
    },
    {
      id: "sr:match:22650877",
      scheduled: "2021-03-03T20:00:00+00:00",
      start_time_tbd: false,
      status: "not_started",
      tournament_round: {
        type: "group",
        number: 28,
        phase: "regular season",
      },
      season: {
        id: "sr:season:77239",
        name: "Ligue 1 20/21",
        start_date: "2020-08-21",
        end_date: "2021-05-31",
        year: "20/21",
        tournament_id: "sr:tournament:34",
      },
      tournament: {
        id: "sr:tournament:34",
        name: "Ligue 1",
        sport: {
          id: "sr:sport:1",
          name: "Soccer",
        },
        category: {
          id: "sr:category:7",
          name: "France",
          country_code: "FRA",
        },
      },
      competitors: [
        {
          id: "sr:competitor:1642",
          name: "Montpellier HSC",
          country: "France",
          country_code: "FRA",
          abbreviation: "MHS",
          qualifier: "home",
        },
        {
          id: "sr:competitor:1656",
          name: "FC Lorient",
          country: "France",
          country_code: "FRA",
          abbreviation: "FCL",
          qualifier: "away",
        },
      ],
      venue: {
        id: "sr:venue:1275",
        name: "Stade de La Mosson",
        capacity: 22000,
        city_name: "Montpellier",
        country_name: "France",
        map_coordinates: "43.622222,3.811944",
        country_code: "FRA",
      },
    },
    {
      id: "sr:match:22650879",
      scheduled: "2021-03-03T20:00:00+00:00",
      start_time_tbd: false,
      status: "not_started",
      tournament_round: {
        type: "group",
        number: 28,
        phase: "regular season",
      },
      season: {
        id: "sr:season:77239",
        name: "Ligue 1 20/21",
        start_date: "2020-08-21",
        end_date: "2021-05-31",
        year: "20/21",
        tournament_id: "sr:tournament:34",
      },
      tournament: {
        id: "sr:tournament:34",
        name: "Ligue 1",
        sport: {
          id: "sr:sport:1",
          name: "Soccer",
        },
        category: {
          id: "sr:category:7",
          name: "France",
          country_code: "FRA",
        },
      },
      competitors: [
        {
          id: "sr:competitor:1647",
          name: "FC Nantes",
          country: "France",
          country_code: "FRA",
          abbreviation: "FCN",
          qualifier: "home",
        },
        {
          id: "sr:competitor:1682",
          name: "Stade Reims",
          country: "France",
          country_code: "FRA",
          abbreviation: "SDR",
          qualifier: "away",
        },
      ],
      venue: {
        id: "sr:venue:953",
        name: "Stade de La Beaujoire",
        capacity: 37473,
        city_name: "Nantes",
        country_name: "France",
        map_coordinates: "47.255631,-1.525375",
        country_code: "FRA",
      },
    },
    {
      id: "sr:match:22650885",
      scheduled: "2021-03-03T20:00:00+00:00",
      start_time_tbd: false,
      status: "not_started",
      tournament_round: {
        type: "group",
        number: 28,
        phase: "regular season",
      },
      season: {
        id: "sr:season:77239",
        name: "Ligue 1 20/21",
        start_date: "2020-08-21",
        end_date: "2021-05-31",
        year: "20/21",
        tournament_id: "sr:tournament:34",
      },
      tournament: {
        id: "sr:tournament:34",
        name: "Ligue 1",
        sport: {
          id: "sr:sport:1",
          name: "Soccer",
        },
        category: {
          id: "sr:category:7",
          name: "France",
          country_code: "FRA",
        },
      },
      competitors: [
        {
          id: "sr:competitor:1659",
          name: "RC Strasbourg Alsace",
          country: "France",
          country_code: "FRA",
          abbreviation: "RCS",
          qualifier: "home",
        },
        {
          id: "sr:competitor:1653",
          name: "AS Monaco FC",
          country: "France",
          country_code: "FRA",
          abbreviation: "ASM",
          qualifier: "away",
        },
      ],
      venue: {
        id: "sr:venue:847",
        name: "Stade de La Meinau",
        capacity: 29200,
        city_name: "Strasbourg",
        country_name: "France",
        map_coordinates: "48.560083,7.755000",
        country_code: "FRA",
      },
    },
    {
      id: "sr:match:23204345",
      scheduled: "2021-03-03T20:15:00+00:00",
      start_time_tbd: false,
      status: "not_started",
      tournament_round: {
        type: "group",
        number: 29,
        phase: "regular season",
      },
      season: {
        id: "sr:season:77179",
        name: "Premier League 20/21",
        start_date: "2020-09-12",
        end_date: "2021-05-24",
        year: "20/21",
        tournament_id: "sr:tournament:17",
      },
      tournament: {
        id: "sr:tournament:17",
        name: "Premier League",
        sport: {
          id: "sr:sport:1",
          name: "Soccer",
        },
        category: {
          id: "sr:category:1",
          name: "England",
          country_code: "ENG",
        },
      },
      competitors: [
        {
          id: "sr:competitor:7",
          name: "Crystal Palace FC",
          country: "England",
          country_code: "ENG",
          abbreviation: "PAL",
          qualifier: "home",
        },
        {
          id: "sr:competitor:35",
          name: "Manchester United FC",
          country: "England",
          country_code: "ENG",
          abbreviation: "MNU",
          qualifier: "away",
        },
      ],
      venue: {
        id: "sr:venue:10",
        name: "Selhurst Park",
        capacity: 25073,
        city_name: "London",
        country_name: "England",
        map_coordinates: "51.398333,-0.085556",
        country_code: "ENG",
      },
    },
  ],
};

export const noGames = {
  generated_at: "2021-03-26T15:34:53+00:00",
  schema: "",
  message: "No events scheduled for this date.",
};
